call git clone --branch 0.0.3 git@github.com:AlephVault/unity-support.git  ..\unity-support
call git clone --branch 0.0.1 git@github.com:AlephVault/unity-support-generic.git ..\unity-support-generic
call git clone --branch 0.0.2 git@github.com:AlephVault/unity-boilerplates.git ..\unity-boilerplates
call git clone --branch 0.0.1 git@github.com:AlephVault/unity-layout.git ..\unity-layout
call git clone --branch 0.0.2 git@github.com:AlephVault/unity-menu-actions.git ..\unity-menu-actions
call git clone --branch 0.0.1 git@github.com:AlephVault/unity-soundaround.git ..\unity-soundaround
call git clone --branch 0.0.4 git@github.com:AlephVault/unity-spriteutils.git ..\unity-spriteutils
call git clone --branch 0.0.1 git@github.com:AlephVault/unity-textureutils.git ..\unity-textureutils
call git clone --branch 0.0.2 git@github.com:AlephVault/unity-backpack.git ..\unity-backpack
call git clone --branch 0.0.2 git@github.com:AlephVault/unity-gabtab.git ..\unity-gabtab
call git clone --branch 0.0.8 git@github.com:AlephVault/unity-windrose.git ..\unity-windrose
call git clone --branch 0.0.4 git@github.com:AlephVault/unity-windrose-biomes.git ..\unity-windrose-biomes
call git clone --branch 0.0.2 git@github.com:AlephVault/unity-windrose-backpack-plugin.git ..\unity-windrose-backpack-plugin
call git clone --branch 0.0.2 git@github.com:AlephVault/unity-windrose-gabtab-plugin.git ..\unity-windrose-gabtab-plugin
call git clone --branch 0.0.4 git@github.com:AlephVault/unity-windrose-spriteutils.git ..\unity-windrose-spriteutils
call git clone --branch 0.0.3 git@github.com:AlephVault/unity-windrose-neighbourteleports.git ..\unity-windrose-neighbourteleports
call git clone --branch 0.0.1 git@github.com:AlephVault/unity-windrose-cubeworlds.git ..\unity-windrose-cubeworlds
call git clone --branch 0.0.4 git@github.com:AlephVault/unity-windrose-refmapchars.git ..\unity-windrose-refmapchars
call git clone --branch 0.0.1 git@github.com:AlephVault/unity-windrose-lpcbiomes.git ..\unity-windrose-lpcbiomes

